# Generated by Django 5.2.5 on 2025-08-13 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autore',
            name='utente_collegato',
        ),
        migrations.RemoveField(
            model_name='utente',
            name='tipologiautente',
        ),
        migrations.AddField(
            model_name='utente',
            name='autore',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='libreria.autore'),
        ),
    ]
