# Generated by Django 5.2.5 on 2025-08-21 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0002_remove_autore_utente_collegato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autori',
            field=models.ManyToManyField(related_name='libri', to='libreria.autore'),
        ),
        migrations.AlterField(
            model_name='recensione',
            name='idlibro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recensioni', to='libreria.libro'),
        ),
        migrations.AlterField(
            model_name='utente',
            name='immagine',
            field=models.ImageField(blank=True, null=True, upload_to='profili/'),
        ),
    ]
