# Generated by Django 5.2.5 on 2025-08-29 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0003_alter_libro_autori_alter_recensione_idlibro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='autore',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventi', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='utente',
            name='autore',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='utente', to='libreria.autore'),
        ),
    ]
